use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMUserCenterManager_Example' do
  pod 'AHFMUserCenterManager', :path => '../'

  target 'AHFMUserCenterManager_Tests' do
    inherit! :search_paths

    
  end
end
